# Generated by Django 4.2.2 on 2023-07-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
            options={
                'verbose_name': 'Начислять бонусов',
                'verbose_name_plural': 'Начислять бонусов',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.CharField(max_length=120, unique=True, verbose_name='qr код')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='Принят')),
                ('is_reject', models.BooleanField(default=False, verbose_name='Отклонен')),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонусный баланс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='users.users', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='CodeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, unique=True, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Проверочное слово',
                'verbose_name_plural': 'Проверочные слова',
            },
        ),
        migrations.CreateModel(
            name='Gtin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Gtin',
                'verbose_name_plural': 'Gtin',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('name', models.TextField(verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('check_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='checks.check', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
