# Generated by Django 4.2.2 on 2023-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='баланс'),
        ),
    ]
