# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_alter_bonus_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=10),
            preserve_default=False,
        ),
    ]
