# Generated by Django 4.2.2 on 2023-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_product_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
