# Generated by Django 4.2.2 on 2023-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Код'),
        ),
    ]
