# Generated by Django 4.2.2 on 2023-07-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycode', models.CharField(max_length=120, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Забанен')),
                ('registered_at', models.DateTimeField(auto_now=True, verbose_name='Зарегистрироан')),
                ('tg_id', models.CharField(max_length=120, unique=True, verbose_name='Телеграм id')),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонусны')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.code', verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
