# Generated by Django 4.2.2 on 2023-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=32, max_length=120),
            preserve_default=False,
        ),
    ]
