# Generated by Django 4.2.2 on 2023-06-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
