# Generated by Django 4.2.2 on 2023-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_alter_users_bonus_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
            ],
        ),
    ]
