# Generated by Django 4.2.2 on 2023-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='excel_file',
            field=models.FileField(default=32, upload_to='excel_files', verbose_name='Файл Excel'),
            preserve_default=False,
        ),
    ]
