# Generated by Django 4.2.2 on 2023-07-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_codeword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeword',
            name='word',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
