# Generated by Django 4.2.2 on 2023-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_code_keycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files', verbose_name='Файл Excel'),
        ),
    ]
