# Generated by Django 4.2.2 on 2023-07-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_check_is_accepted_check_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('check_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.check')),
            ],
        ),
    ]
