# Generated by Django 4.2.2 on 2023-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_is_admin_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='processing', max_length=20),
        ),
    ]
