# Generated by Django 4.2.2 on 2023-07-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_output_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='output',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='users.users'),
        ),
    ]
