# Generated by Django 4.2.2 on 2023-07-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
            options={
                'verbose_name': 'Минимальный вывод',
                'verbose_name_plural': 'Минимальный вывод',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='processing', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='users.users', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вывод',
                'verbose_name_plural': 'Выводы',
            },
        ),
    ]
