# Generated by Django 4.2.2 on 2023-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0003_output_send_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='send_data',
            field=models.CharField(max_length=200, verbose_name='Куда отправлять'),
        ),
    ]
